let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Chicken Briyani",
    price: 245,
    desc: "Biryani is a mixed rice dish originating among the Muslims of the Indian subcontinent. It is made with Indian spices, rice, and usually some type of meat or in some cases without any meat, and sometimes, in addition, eggs and potatoesg.",
    img: "images/img-1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Sandwich",
    price: 100,
    desc: "A sandwich is a food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread.",
    img: "images/img-2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Chicken Kebab",
    price: 225,
    desc: "A kebab (Bangladeshi, Indian, Pakistani and Arabian) is a type of cooked meat dish that originates from cuisines of the Middle East.",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Tandoori Chicken",
    price: 300,
    desc: "Tandoori chicken is a popular Indian dish where marinated chicken is grilled to perfection in a Tandoor, a cylindrical clay oven.",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Shawarma",
    price: 125,
    desc: "Shawarma is a popular Middle Eastern dish that originated in the Ottoman Empire, consisting of meat cut into thin slices, stacked in a cone-like shape, and roasted on a slowly-turning vertical rotisserie or spit.",
    img: "images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Pasta",
    price: 200,
    desc: "Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking.",
    img: "images/img-6.jpeg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Chicken Noodles",
    price: 250,
    desc: "Chicken noodles are a delicious flavor packed meal of stir fried noodles, chicken, vegetables and sauces. Made in Chinese Hakka Style.",
    img: "images/img-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Paneer Butter Masala",
    price: 245,
    desc: "Paneer butter masala, also known as butter paneer is a rich & creamy curry made with paneer, spices, onions, tomatoes, cashews and butter.",
    img: "images/img-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Meals",
    price: 185,
    desc: "Curry is one of India's most popular and well-known dishes. Tomato-based curries are known as the ultimate comfort food in India, and countries all over the world have adopted this opinion too.",
    img: "images/img-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Pizza",
    price: 420,
    desc: "Pizza is a dish of Italian origin consisting of a usually round, flat base of leavened wheat-based dough topped with tomatoes, cheese, and often various other ingredients, which is then baked at a high temperature, traditionally in a wood-fired oven.",
    img: "images/img-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Bread Omelette",
    price: 55,
    desc: "A bread recipe that can be adapted to become a complete meal is that of a bread omelette. Creamy eggy filling, seasoned with scintillating flavours",
    img: "images/img-11.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Chapati",
    price: 50,
    desc: "Chapati, also known as roti, rooti, rotli, rotta, safati, shabaati, phulka, chapo, poli, and roshi, is an unleavened flatbread originating from the Indian.",
    img: "images/img-12.jpg",
  },
];
